# Generated by Django 4.1.4 on 2023-02-21 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='creado_el',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.TextField(default='por_hacer', max_length=100),
        ),
    ]
