# Generated by Django 4.1.4 on 2023-02-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_tarea_creado_el_alter_tarea_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='terminado_el',
            field=models.DateField(auto_now=True),
        ),
    ]
