# Generated by Django 4.1.4 on 2023-02-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_tarea_terminado_el'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='terminado_el',
            field=models.DateField(),
        ),
    ]
