# Generated by Django 4.1.4 on 2023-02-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_remove_tarea_terminado_el_tarea_modificado_el'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='creado_el',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='modificado_el',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
